### ISSUE TITLE
Can't release sorl-thumbnail

### ISSUE THREAD

**Issue by camilonova** [jazzband-roadies/help#105]
I can't release 12.5.0 version of sorl-thumbnail trough the jazzband site.

![screen shot 2018-09-15 at 10 23 23 am](https://user-images.githubusercontent.com/202559/45587877-695a4780-b8d1-11e8-9cc6-79fcd9bed13a.png)

Seems related: https://travis-ci.org/jazzband/sorl-thumbnail/jobs/428373120

**Comment by camilonova** [comment]
I just tried again and it worked.

**Comment by jezdez** [comment]
Dang, I've seen this a bit and I'm going to have to look into this. The site is deployed using Docker so maybe something about how the files are mounted via volumes fails. I'll look into it..

**Comment by camilonova** [comment]
I'll try again to cut a release if the build running two days ago on travis finishes this year :(

**Comment by jezdez** [comment]
This should work as expected again.
