### ISSUE TITLE
Create issue templates for project proposals

### ISSUE THREAD

**Issue by jezdez** [jazzband-roadies/help#124]
The proposal in https://github.com/jazzband/roadies/issues/123 has a good format, following the [Jazzband guidelines](https://jazzband.co/about/guidelines).

**Comment by atugushev** [comment]
This is a good issue template indeed 👍

**Comment by PiDelport** [comment]
If anyone with the access wants to tackle this:

* https://help.github.com/en/articles/creating-issue-templates-for-your-repository

**Comment by jstockwin** [comment]
I'll have a go at this! I suspect those with more experience may suggest some changes to my wording, but I'll make my best-guess based on how I understand the process, and you can always request changes :+1:

**Comment by jezdez** [comment]
@jstockwin Thank you! There is also #192 which isn't bad.

**Comment by jstockwin** [comment]
@jezdez Cool, I created a few templates in #197 based on your examples, and also from the website. Let me know what you think!
