### ISSUE TITLE
Proposing django-voting

### ISSUE THREAD

**Issue by PiDelport** [jazzband-roadies/help#136]
* Repo: https://github.com/PiDelport/django-voting

As explained in https://github.com/PiDelport/django-voting/issues/13, I'm no longer using or actively maintaining this package, and @stephendwolff expressed interest in helping to get it in shape for Jazzband.

[Guidelines](https://jazzband.co/about/guidelines) criteria:

- **Viability** - Dates back to 2007 on [Google Code](https://code.google.com/archive/p/django-voting/), has been maintained until ~2017, has pending PRs and activity.
- **Documentation** - [docs/overview.rst](https://github.com/PiDelport/django-voting/blob/master/docs/overview.rst)
- **Tests** - [tests](https://github.com/PiDelport/django-voting/tree/master/tests)

To do:

- [ ] **Conduct**
- [ ] **Contributing Guidelines**
- [ ] **Badges**

To transfer to Jazzband:

- [ ] PyPI - https://pypi.org/project/django-voting/
- [ ] Travis - https://travis-ci.org/PiDelport/django-voting

**Comment by PiDelport** [comment]
I may have jumped the gun here: I thought requesting the transfer would just request it, and have the Jazzband bot take some actions… but the repo is transferred now.

Is that okay?

**Comment by jezdez** [comment]
Hmm, somethng went wrong during the transfer with the webhooks.. investigating.

As an aside, have you reached out to @brosner about transferring the original project? I'm not a fan of us maintaining forks, since that kind of defeats the purpose :-/

**Comment by stephendwolff** [comment]
I think the original project has been archived: https://code.google.com/archive/p/django-voting/#! and never got past about Django 1.1. 
I just stepped in with a PR to get it working with Django 1.11 (from 1.8 or so). It would need another update to get it up to the current LTS i think

**Comment by jezdez** [comment]
Sure, what I'm saying is that we can ask @brosner to do the transfer, then push the changes in @PiDelport's fork into that repo. Or maybe ask GitHub support to remove the fork boolean.

**Comment by stephendwolff** [comment]
Ah - i hadn't realised @PiDelport's was a fork - as it is published on PyPI

**Comment by jezdez** [comment]
It's probably from a time when repos weren't allowed to be transferred.

**Comment by jezdez** [comment]
Downside of using brosner's repo would be we'd loose all tickets/PRs in @PiDelport's repo. @PiDelport what do you think?

**Comment by PiDelport** [comment]
Hmm, have probably diverged so far from @brosner's original repo that it doesn't really gain us anything to try and transfer that?

It's probably simpler to just create a fresh GitHub repo for Jazzband, and transfer the existing Git history and open branches / PRs into that. (There's not a lot to transfer.)

@jezdez: Does that sound good to you?

**Comment by jezdez** [comment]
@PiDelport Yeah, that'd work for me.

**Comment by PiDelport** [comment]
@jezdez: Okay, cool!

It doesn't look like I can transfer the repo back out of the Jazzband organisation; I assume you can? You could transfer it back to me, then we can create a new empty `jazzband/django-voting` and I'll push and transfer things to it?

**Comment by stephendwolff** [comment]
@jezdez, @PiDelport, I should have a bit of time to work on this in May - do i make a fork of this, then a PR for any updates necessary to get all the 'Guidelines' addressed?

**Comment by hramezani** [comment]
Any update? I can work on this. what should I do?

**Comment by jezdez** [comment]
Hey friends, I'm closing this in favor of jazzband/django-voting#17. Any help to get this over the finish line is always much appreciated.
