### ISSUE TITLE
tablib: CI for release

### ISSUE THREAD

**Issue by claudep** [jazzband-roadies/help#169]
One of the point of https://github.com/jazzband/tablib/issues/378 is:
 * Set up CI for Jazzband project releases if needed and open ticket if yes

I'd like to ask for that with this ticket, thanks!

**Comment by aleksihakli** [comment]
Hi! I just took a look at the CI generally and noticed that [Python 2.7 builds are failing](https://travis-ci.org/jazzband/tablib/jobs/593930236). It would be suitable to drop Python 2.7 from the test matrix entirely as it's being deprecated at the moment and won't be supported beyond December, 2020. Just dropping the 2.7 line from the [`.travis.yml`](https://github.com/jazzband/tablib/blob/master/.travis.yml) file would be suitable.

**Comment by claudep** [comment]
The build is failing for a specific PR (which targets the post-2.7 time), not for current master.

**Comment by claudep** [comment]
Is there some time frame for this to be resolved? Because I could also ask current maintainers to add me as maintainer so as I can make releases in between.

**Comment by jezdez** [comment]
@claudep Sure thing, let's select a project lead in https://github.com/jazzband/tablib/issues/378 first, then I can set this up quickly.

**Comment by jezdez** [comment]
Ah, I think this is fixed.
