### ISSUE TITLE
Proposal: django-defender

### ISSUE THREAD

**Issue by kencochrane** [jazzband-roadies/help#170]
Hello, @aleksihakli has suggested that I move https://github.com/kencochrane/django-defender/ over to Jazzband, and this issue is to discuss if you are interested in accepting the project.

This discussion originated here: https://github.com/kencochrane/django-defender/issues/121

I looked over the guidelines and they look good, and the project has most of the requirements already and only needs a few changes before it can be moved over. 
- Move docs from README to sphinx docs and setup ReadTheDocs integration
- Add a contributors file to the repo.

If you decide to accept django-defender then we can look at making the required changes.

Let me know if you have any questions.

**Comment by jezdez** [comment]
Yep, the project looks like it fits well into Jazzband, thank you for proposing it. Given the original ticket https://github.com/kencochrane/django-defender/issues/121 that discusses to possibly merge or further integrate it with django-axes I'm hoping that @aleksihakli and @camilonova can help figure out a common roadmap.

@kencochrane Feel free to transfer the repo as there will be a ticket auto-created for the post-transfer TODOs anyways. Welcome to Jazzband 🎶

**Comment by kencochrane** [comment]
@jezdez thank you!

**Comment by kencochrane** [comment]
I transferred over the repo, I'll close this issue since it is complete, and we can work off the new issue that was auto-created in the defender repo.

**Comment by aleksihakli** [comment]
I think there's at least the prospect of joint maintenance for the projects that seems like a decent idea to me. Since both projects specialize in securing logins, cross checking tickets and PRs and utilizing the security interests of Jazzband members could be good ways to build a common ground and interest for a more secure tomorrow :)
