### ISSUE TITLE
Implement Jazzband PyPI release pipeline for django-defender

### ISSUE THREAD

**Issue by aleksihakli** [jazzband-roadies/help#174]
Relates to https://github.com/jazzband/django-defender/issues/138

django-defender requires a Jazzband repository and a valid PyPI upstream upload configuration in order to enable the pipelines.

I believe @kencochrane is the obvious lead in the project.

**Comment by jezdez** [comment]
This is done.

**Comment by aleksihakli** [comment]
Thanks @jezdez!
