### ISSUE TITLE
django-flatblocks repository is a fork

### ISSUE THREAD

**Issue by martey** [jazzband-roadies/help#175]
https://github.com/jazzband/django-flatblocks/ is a fork of the previous maintainer's repository at https://github.com/zerok/django-flatblocks. This makes the project less visible, is confusing for new contributors, and disincentivizes contributions.

I think it would be good if a roadie could contact Github Support and [request that the repository be detached](https://help.github.com/en/github/setting-up-and-managing-your-github-profile/why-are-my-contributions-not-showing-up-on-my-profile#commit-was-made-in-a-fork) and made into a source repo with a new network. Once this is done, we could also ask @zerok to ask Github Support to make their repository a fork of the jazzband repo, although this is not strictly necessary.

**Comment by zerok** [comment]
Sounds good to me :)

Cheers,
Horst

**Comment by jezdez** [comment]
Thank you @martey, this is a great idea. I've requested the detaching. 🙌 

@zerok I'll let you know when this is done.

**Comment by jezdez** [comment]
This is done now, thanks again for the idea @martey!

@zerok GitHub support was pretty fast, would you mind requesting it?

**Comment by jezdez** [comment]
@zerok Anything I can help you with?

**Comment by zerok** [comment]
@jezdez Argh, sorry, missed your previous comment. I'll update my repo's README this weekend and then archive it :)

**Comment by jezdez** [comment]
@zerok Would you also mind asking support to reattach it to the network of the Jazzband fork?

**Comment by zerok** [comment]
Done :)

**Comment by zerok** [comment]
Seems like support cannot hang a repo into a completely different network. Sorry 😔But links etc. are in place 🙂

**Comment by martey** [comment]
I'm closing this because I think everything possible that can be done has been. Thanks @jezdez and @zerok for taking care of this!
