### ISSUE TITLE
Release django-authority to pypi

### ISSUE THREAD

**Issue by safwanrahman** [jazzband-roadies/help#183]
Hi,
I have made a relase of django-authority in github. Can anyone please push the release to pypi?

**Comment by jezdez** [comment]
This is done: https://pypi.org/project/django-authority/0.14/

**Comment by benspaulding** [comment]
@jezdez Thank you!

**Comment by jezdez** [comment]
@benspaulding Happy to, this took a bit longer in actual release work since there were still some subtle build problems. Please let me know if you see any regressions..
