### ISSUE TITLE
Can somebody make me admin on django-user-sessions?

### ISSUE THREAD

**Issue by Bouke** [jazzband-roadies/help#184]
So 3 weeks ago django-user-sessions has been migrated to jazzband. Apparently in the transition I've lost admin permissions and now I cannot merge pull requests anymore. I've tried reaching out to @jezdez, but no response so far. Anyone here that can help me out?

**Comment by jezdez** [comment]
Hey @Bouke, that is unusual, it's correct that you lost admin permissions, but merging PRs should be unaffected since you are a member of the Jazzband org: 
<img width="759" alt="Screen-Shot-2020-02-15-18-16-02 18" src="https://user-images.githubusercontent.com/1610/74592216-6b24bf00-501f-11ea-99b0-a2d28dc1e068.png">

**Comment by Bouke** [comment]
@jezdez I still can’t merge PRs. E.g. https://github.com/jazzband/django-user-sessions/pull/108.
![41BF03C9-0D57-46F5-A48B-A229E37521FB](https://user-images.githubusercontent.com/235882/75120848-fa207f80-568e-11ea-9957-d00dc9f9e3a6.jpeg)

**Comment by Bouke** [comment]
Hi @jezdez. We’re now almost 2 months in, but I’m still unable to merge PRs and am very much blocked. Can you please help me get unblocked?

**Comment by Bouke** [comment]
@jezdez The problem is that the PR checks are not configured correctly. As I have no admin permissions, I can't resolve these problems. Either you fix those permissions, or you make me admin, or you transfer the repository back to me. Your choice :).

https://github.community/t5/How-to-use-Git-and-GitHub/Cannot-merge-PR-quot-some-checks-haven-t-completed-yet-quot-but/m-p/50127#M10871

> The solution is easy, but only by someone with admin rights. They need to edit the branch rules and remove the "Expected" checkbox from the two stale checks.

**Comment by jezdez** [comment]
Aha, thanks for letting me know what the problem is, I didn't realize that back when I first replied. I just removed the check requirements for the master branch. That should fix the immediate problem.
