### ISSUE TITLE
request to become additional lead for django-oauth-toolkit

### ISSUE THREAD

**Issue by n2ygk** [jazzband-roadies/help#186]
My employer relies on django-oauth-toolkit for several of our core projects. I've been a contributor  and committer to the project and would like to volunteer as a project lead to supplement @MattBlack85 who is currently the only lead. There are a bunch of webhooks that need to be [fixed](https://github.com/jazzband/django-oauth-toolkit/issues/550)and we are trying to roll out a new release as well.

Thanks.

**Comment by n2ygk** [comment]
oops didn't label this properly.

**Comment by n2ygk** [comment]
Actually I did it right, the lead label just doesn't show up right away I guess...

**Comment by n2ygk** [comment]
@jezdez FYI - I've released [django-oauth-toolkit 1.3.0](https://github.com/jazzband/django-oauth-toolkit/releases/tag/1.3.0) and need to git it into pypi and rtd.

**Comment by n2ygk** [comment]
@jezdez A reminder that I still need this capability as there is nobody currently on the project who is able to configure github hooks, etc. I hope your health is OK and that you are able to make me a lead on this project and also consider the offers of others to assist as a roadie. A single-resource supporting all of jazzband just doesn't work.

**Comment by jezdez** [comment]
Thanks @n2ygk, I saw your tweet at https://twitter.com/n2ygk/status/1305864224317542402 about me not responding to your ticket and hence Jazzband being a failed experiment. Thank you for your feedback.

@MattBlack85 Are you okay with @n2ygk becoming second lead to the project?

**Comment by MattBlack85** [comment]
absolutely @jezdez

**Comment by n2ygk** [comment]
@jezdez do you prefer being pinged here or DM'd to remind you? Thanks.

**Comment by jezdez** [comment]
@n2ygk Pinging me here is okay or via DM works both, remember that issue notifications are just another inbox that I need to go through. So use your own judgement when it's too much noise over signal :)

I've added you to the project, finally! 🎊
