### ISSUE TITLE
labels not available when opening issues here

### ISSUE THREAD

**Issue by n2ygk** [jazzband-roadies/help#188]
https://jazzband.co/about/releases says to open a new issue with various labels. I tried this in #187 but apparently only a contributor to this repo is able to add labels. @jezdez is the only contributor.  Documentation error? Something changed?

**Comment by jstockwin** [comment]
This can be closed as it was fixed in #197 -> choosing the correct template when opening a PR should apply the correct label. (I don't have permissions to close it).

I have created https://github.com/jazzband-roadies/website/issues/730 to handle the documentation side of this.

**Comment by jezdez** [comment]
Thanks again for your help with this @jstockwin! ❤️
