### ISSUE TITLE
please add me as a lead for django-flatblocks

### ISSUE THREAD

**Issue by martey** [jazzband-roadies/help#191]
https://jazzband.co/projects/django-flatblocks shows that the project has no current leads.

I don't believe that the [currently released version](https://pypi.org/project/django-flatblocks/0.9.4/) is compatible with any currently supported version of Django except 1.11. Since the PyPi page does not show `jazzband` as a maintainer, I think it is not set up for automated PyPi releases either.

If I am added as a lead, I will work to get release automation working so that a release compatible with Django 2.2 and 3.0 can be made.

**Comment by jezdez** [comment]
Hey @martey, my apologies for getting back to you after this time, are you still interested in this?

As the other significant contributors to the package I just want to make sure @zerok and @funkybob are okay with making @martey project lead?

FWIW I've recommended in the past to add multiple leads to a project to be able to load balance in case of life getting in the way. What do you say?

**Comment by funkybob** [comment]
Thanks for double checking, @jezdez 

That was a main part of why I passed this onto Jazzband- I no longer had the interest/motivation/headspace to maintain it.

I'm absolutely pleased for someone else to take over maintainership.

**Comment by jezdez** [comment]
> Thanks for double checking, @jezdez
> 
> That was a main part of why I passed this onto Jazzband- I no longer had the interest/motivation/headspace to maintain it.
> 
> I'm absolutely pleased for someone else to take over maintainership.

So happy to hear that, thank you for responding so quickly!

**Comment by jezdez** [comment]
@martey I've made you project lead, please let me know if you've reconsidered since March. Thank you!

**Comment by zerok** [comment]
Hey 👋 Sorry for the late response! I'm absolutely fine with that! 🙂

**Comment by martey** [comment]
@jezdez, thanks for responding to me. I am still interested on this and will work on creating a new release for django-flatblocks!

**Comment by jezdez** [comment]
@martey Excellent, thanks!
