### ISSUE TITLE
Is jsonmodels dead?

### ISSUE THREAD

**Issue by paulopaixaoamaral** [jazzband-roadies/help#195]
Hello,

The developers in my company are heavy users of the jsonmodels project (https://github.com/jazzband/jsonmodels), but I'm wondering if the project is abandoned or not. 
I opened an issue (https://github.com/jazzband/jsonmodels/issues/136) a few weeks ago and haven't got any response yet, so I was wondering if this is an abandoned project or are you looking for maintainers?

**Comment by hugovk** [comment]
Hi @paulopaixaoamaral!

The idea of Jazzband:

> Jazzband is a collaborative community to share the responsibility of maintaining Python-based projects.

It could be that those who were keeping an eye on it are not in a position to do so right now, so more maintainers would be helpful. 

So it might be a good idea to join Jazzband yourself, if you're in a position to lend a hand! 

Let's also ping @beregond (and see https://github.com/jazzband/jsonmodels/issues/133). 

Thanks!

**Comment by paulopaixaoamaral** [comment]
Hey, I noticed this had a "question" label added, and just wanted to be clear that I wouldn't mind being a project lead in this project (provided the original leaders are happy with this). I also work closely with @jstockwin who said he would be happy to be a project lead with me, so it would be two of us working on this.

**Comment by camilonova** [comment]
@paulopaixaoamaral great, just open an issue asking to become the project lead and that would be it.

Thank you.

**Comment by paulopaixaoamaral** [comment]
Closing as we have requested to become project leads for jsonmodels in https://github.com/jazzband-roadies/help/issues/207
