### ISSUE TITLE
Help for enable the auto-release mechanism in django-cities-light

### ISSUE THREAD

**Issue by marianoeramirez** [jazzband-roadies/help#199]
We need some help on https://github.com/jazzband/django-cities-light to enable the auto-release mechanism via the Jazzband. 

I read this documentation https://jazzband.co/about/releases, but is not clear to me how to enable the auto-release mechanism. If someone can help with this will be very helpful. Thanks in advance.

**Comment by marianoeramirez** [comment]
We just need some help to finish with the configuration of the password for auto-deploy, the process is already running because I copied the configuration from Django-axes. But I suppose still require the right password and configuration on the site, https://travis-ci.org/github/jazzband/django-cities-light/jobs/722731202.

**Comment by jezdez** [comment]
@marianoeramirez I've left a comment in https://github.com/jazzband/django-cities-light/issues/210 to move this forward. Basically we need a project lead first before enabling this feature.

**Comment by jezdez** [comment]
This was fixed a while ago.
