### ISSUE TITLE
 Set up CI for Jazzband project releases for PrettyTable

### ISSUE THREAD

**Issue by hugovk** [jazzband-roadies/help#202]
The last [PrettyTable](https://github.com/jazzband/prettytable/) release was in [2013](https://pypi.org/project/PrettyTable/#history) and I'm all set to make a new release.

Please could you help with this?

* [x]  Set up CI for Jazzband project releases if needed and open ticket if yes
* [ ] Alternatively, please add `hugovk` as a maintainer on https://pypi.org/project/PrettyTable/
* [ ] Another option to consider is a [PEP 541 transfer](https://www.python.org/dev/peps/pep-0541/)

Refs:
* https://github.com/jazzband/prettytable/issues/18 "New PyPI release?"
* https://github.com/jazzband/prettytable/issues/22 "Implement Jazzband guidelines for prettytable"

Thank you!

**Comment by hugovk** [comment]
I should be all set to do a standard Jazzband release now, thanks!

**Comment by jezdez** [comment]
@hugovk Thanks for your help and patience! ❤️
