### ISSUE TITLE
Call to maintain newspapers

### ISSUE THREAD

**Issue by Bachstelze** [jazzband-roadies/help#204]
The package `Newspaper3k: Article scraping & curation` is calling for maintaining. Have a look at the current discussion https://github.com/codelucas/newspaper/issues/813
Any suggestions are welcome how to ensure the development and to fund the developers as well as the original content creators.

**Comment by jezdez** [comment]
@Bachstelze Please use the new Project proposal issue template: https://github.com/jazzband-roadies/help/issues/new?assignees=&labels=proposal&template=proposal.md&title=Proposal%3A+%3CPACKAGE+NAME%3E
