### ISSUE TITLE
Transfer django-cities-light to an org commited to free software hackers

### ISSUE THREAD

**Issue by jpic** [jazzband-roadies/help#205]
Sorry, I thought Jazzband would be a nice experience, but I didn't understand the terms & conditions properly.

Despite the Jazzband conditions, we have seen how members may freely express their resent against "pale male", which, being an arabic half-time shemale myself, chocks me as gender AND sexual discrimination to which I firmly oppose.

Most importantly, Jazzband opposes to freelancers and companies offering paid support for the free software, including those they created, on the basis of vagues clauses that would not stand a chance a court, but that may impress younger hackers and prevent them from offering paid support on free software is not acceptable:

![2020-11-04-173251_832x777_scrot](https://user-images.githubusercontent.com/94636/98236661-feae6f00-1f63-11eb-854e-35a019895c85.png)

Apparently, Jazzband wants to apply their own terms in conditions over the software license, therefore changing its terms, despite advertising as a collaborative effort to help OSS developers, it has a deeper freedom-restricting political agenda that was not advertised.

As such, please transfer the repo back to github.com/yourlabs which is an organization that defends freedom fundamentals ... as well as the law.

Thank you for your support.

For the sake of transparency: this does not change YBS plans to advertise a professional paid service for Jazzband software. YBS will notify you as soon as it's official so that you can take it to court if you see fit. YBS will stand against the conditions changes that Jazzband tries to apply on top of original licenses. Just like YBS defends gender freedom, it will defend hackers freedom, be it the right to offer unofficial repairs for Apple proprietary hardware or free software.

@marianoramirez has accepted by email, YBS also offered payment, which YBS should have done in the first place but we haven't yet a streamlined process, and I had better expectations from the Jazzband experience.

**Comment by jezdez** [comment]
Thanks for asking to transfer the repo back to you, @jpic.

@marianoeramirez could you please confirm that you agreed that the project you are a project lead of is transferred back to @jpic?

**Comment by jezdez** [comment]
For transparency sake, the discussion that @jpic has taken a screenshot of in this ticket has happened in https://github.com/orgs/jazzband/teams/members/discussions/2.

**Comment by marianoeramirez** [comment]
HI, @jezdez I saw the discussion and I am sad that the discussion comes out with this result. 

I agree to transfer the project back to his author.

**Comment by jezdez** [comment]
@marianoeramirez Thank you for the confirmation.

@jpic Just a heads-up that GitHub only allows repo transfers from organizations to the owner of the organization (unclear why) and not someone else (see attached screenshot for proof). This is purely a technical limitation on GitHub's side and I will initiate a second transfer right away from my personal account to you.

<img width="524" alt="CleanShot 2020-11-05 at 14 06 23@2x" src="https://user-images.githubusercontent.com/1610/98245085-afbb0680-1f70-11eb-9804-b03c3fe5d7a0.png">

**Comment by jezdez** [comment]
@jpic I've requested the repo transfer back to you.

<img width="356" alt="CleanShot 2020-11-05 at 14 12 34@2x" src="https://user-images.githubusercontent.com/1610/98245275-f7da2900-1f70-11eb-93f3-500670f18205.png">

**Comment by jpic** [comment]
Thank you very much.

Sorry it didn't work out, no hard feelings I hope (none here).

Have a great day

:tophat:
