### ISSUE TITLE
Should we disable travis?

### ISSUE THREAD

**Issue by camilonova** [jazzband-roadies/help#206]
Recently I've trying to catch up with some PRs in django-constance and sorl-thumbnail using the little time I could get this week, but seeing the build times on travis around 12 hours of waiting time for each build is just unbearable.

https://travis-ci.org/github/jazzband/sorl-thumbnail/builds

https://travis-ci.org/github/jazzband/django-constance/builds

Can we do something about it? It seems travis have a limit on builds or something. I remember before it was instantly, but now is just take too much of the time I don't have, and surely time anyone of the maintainers have.

What should we do?

**Comment by jezdez** [comment]
The short answer is that we'll need to port all repos to GitHub Actions soon. I have set aside a non-trivial amount of time next week to do that conversion of all projects.

**Comment by jezdez** [comment]
I'll use https://github.com/orgs/jazzband-roadies/projects/1 to track the progress..

**Comment by hugovk** [comment]
Already done (tests + deploy):
* https://github.com/jazzband/prettytable

PR for tests, deploy TODO:
* https://github.com/jazzband/tablib/pull/479

**Comment by camilonova** [comment]
@jezdez Awesome. Please put `sorl-thumbnail` in front of the line.

**Comment by jezdez** [comment]
@camilonova Sure thing.
