### ISSUE TITLE
Project Lead: jsonmodels

### ISSUE THREAD

**Issue by paulopaixaoamaral** [jazzband-roadies/help#207]
# Project lead request

Me and my colleague @jstockwin would like to become project leads for this project as we use it extensively (as discussed in https://github.com/jazzband-roadies/help/issues/195).

**Comment by jezdez** [comment]
Thank you both, I've added you as project leads!

**Comment by beregond** [comment]
Hey,

Congrats @paulopaixaoamaral and @jstockwin :)

I was about to pump some work into this project, can we get in touch? I think you have some vision, so we could align.

**Comment by jstockwin** [comment]
Hey @beregond!

Sure, let's have a chat. It would be good for us to understand your vision, and get a top-level overview of the project and its scope.

Drop me an email at jstockwin@gmail.com and we can organize something between the three of us!
