### ISSUE TITLE
Project Lead: django-debug-toolbar

### ISSUE THREAD

**Issue by matthiask** [jazzband-roadies/help#208]
Hi @jezdez 

The release action of django-debug-toolbar fails with a 401 Unauthorized error, either because of missing settings or maybe because I'm not a project lead? See https://github.com/jazzband/django-debug-toolbar/runs/1491294806

It's not enormously important to me since uploading releases directly to PyPI has worked well during the last 4 years but using the official Jazzband release process would be nice too.

**Comment by jezdez** [comment]
Yeah, this was previously not configured so it wasn't ported in the recent GHA work. I've added you to the project as lead. Can you think of someone else who would like to be a lead?

**Comment by jezdez** [comment]
FWIW I've retriggered the 3.2 build and the upload succeeded now.

**Comment by jezdez** [comment]
I only now saw that you did the 3.2 release manually to PyPI already, so you can ignore the release emails you just got FWIW. We can try it out at the next release.

**Comment by matthiask** [comment]
Thank you! Maybe @jdufresne and/or tim-schilling would be interested?

**Comment by tim-schilling** [comment]
If there are no objections, yes I'm interested.

**Comment by jdufresne** [comment]
Thanks @tim-schilling!

I am not in a position to take on such a role at this time, but thanks for thinking of me!

**Comment by jezdez** [comment]
> If there are no objections, yes I'm interested.

I've added you, thank you!

**Comment by jezdez** [comment]
I think this is done for now, feel free to let me know if you want to add anyone else.

**Comment by matthiask** [comment]
Yes, thank you for the quick help!
