### ISSUE TITLE
Change required checks for jsonmodels

### ISSUE THREAD

**Issue by jstockwin** [jazzband-roadies/help#210]
See https://github.com/jazzband/jsonmodels/pull/138#issuecomment-737084598

We need some required checks to be removed to unblock merging of this PR.

Myself, @paulopaixaoamaral and @beregond are project leads, so is it possible that we can have control over these settings ourselves?

**Comment by jezdez** [comment]
> See [jazzband/jsonmodels#138 (comment)](https://github.com/jazzband/jsonmodels/pull/138#issuecomment-737084598)
> 
> We need some required checks to be removed to unblock merging of this PR.

I've removed the branch protection (also removed the coverage ones).

> Myself, @paulopaixaoamaral and @beregond are project leads, so is it possible that we can have control over these settings ourselves?

Sadly GitHub doesn't provide fine-grained control over some settings without exposing security critical settings as well.

**Comment by jstockwin** [comment]
Fingers crossed for https://github.com/github/roadmap/issues/111, then :smile:

**Comment by jezdez** [comment]
> Fingers crossed for [github/roadmap#111](https://github.com/github/roadmap/issues/111), then 😄

Note the item that I  made bold (which won't apply to Jazzband's non-Enterprise GitHub.com use):

> This functionality provides Role-based access control (RBAC) support in **GitHub Enterprise**.

**Comment by jstockwin** [comment]
Ah, sad. Well, thanks for changing the settings anyway, we'll try not to need them changing too often :wink:

**Comment by jezdez** [comment]
> Ah, sad. Well, thanks for changing the settings anyway, we'll try not to need them changing too often 😉

😬
