### ISSUE TITLE
Tablib: Enable ReadTheDocs autobuild for PRs 

### ISSUE THREAD

**Issue by hugovk** [jazzband-roadies/help#211]
@jezdez Please could you enable "Autobuild Documentation for Pull Requests" for https://github.com/jazzband/tablib?

This will help us review docs changes in PRs before merge.

Instructions here:

https://docs.readthedocs.io/en/stable/guides/autobuild-docs-for-pull-requests.html

Thank you!

cc @claudep

**Comment by jezdez** [comment]
Done!
