### ISSUE TITLE
adjust project settings for improvement to django-oauth-toolkit github actions

### ISSUE THREAD

**Issue by n2ygk** [jazzband-roadies/help#321]
Hi @jezdez,

Can you please look at https://github.com/jazzband/django-oauth-toolkit/pull/1219 and review the project settings for this improvement to github actions if you approve of the change. If not, we can cancel it and live with the status quo.

Thanks.

**Comment by hugovk** [comment]
Changes look good. 👍 

To ease future maintainence burden, I suggest adding a no-op job that depends on the main job, and just echoes a success message.

Then the CI can just mark the no-op job as required. Then, when new versions are released and EOL versions are dropped, we aren't blocked on a roadie bottleneck to adjust the settings. 

For example:

https://github.com/hugovk/norwegianblue/blob/71fcbb570406f27d11c9b91f22fec49cfbf2ef69/.github/workflows/test.yml#L49-L55

**Comment by jezdez** [comment]
Sounds like a good idea, I've looked at the change. It's a good idea.

**Comment by n2ygk** [comment]
@jezdez @dopry where to we stand with this? Should you add @hugovk's suggestion?

**Comment by jezdez** [comment]
@n2ygk Yep, I said as much in https://github.com/jazzband/django-oauth-toolkit/pull/1219#issuecomment-1346173343.

As a slight alteration of the plan, it might be useful to use https://github.com/test-summary/action to print out information about the test run.

**Comment by n2ygk** [comment]
@jezdez so I believe only you can implement this change, is that correct? If so, please do!

**Comment by dopry** [comment]
@jezdez I've added the success job. Can you update the required checks on the branch protection now?

**Comment by jezdez** [comment]
Done!

**Comment by dopry** [comment]
awesome. thank you.
