### ISSUE TITLE
Project Lead: django-hosts

### ISSUE THREAD

**Issue by hramezani** [jazzband-roadies/help#322]
# Project lead request

[@timgraham would like to step down from the leading django-hosts](https://github.com/jazzband/django-hosts/issues/144), I can help as a lead of this project. 

I am project lead in [django-auditlog](https://github.com/jazzband/django-auditlog) and [django-voting](https://github.com/jazzband/django-voting)

**Comment by jezdez** [comment]
Done! Fixes https://github.com/jazzband/django-hosts/issues/144
