### ISSUE TITLE
PyPI Release: geojson 3.0.0

### ISSUE THREAD

**Issue by rayrrr** [jazzband-roadies/help#326]
# PyPI Release: GeoJSON 3.0.0

The latest release has been tagged and the [changelog](https://github.com/jazzband/geojson/blob/main/CHANGELOG.rst) has been updated.

I am the project lead; if possible, please add me as a maintainer on PyPI (I have the same username there as here) so I can do this myself for future releases. Or is there a fully automatic process now with GitHub Releases? I have not yet tried that.

**Comment by hugovk** [comment]
You probably don't need PyPI access.

The release files [have been uploaded by GitHub Actions](https://github.com/jazzband/geojson/actions/runs/4012584880/jobs/6891137631) to the staging area at https://jazzband.co/projects/geojson, where you can check them, and then release them from there up to PyPI.

More info: https://jazzband.co/about/releases

**Comment by rayrrr** [comment]
Done. Thanks again @hugovk
