### ISSUE TITLE
Transfer-Out: django-cookie-consent

### ISSUE THREAD

**Issue by sergei-maertens** [jazzband-roadies/help#337]
We are basically running into the same issues as #336 - jazzband currently sits in the way to properly maintain and release django-cookie-consent.

I work for https://github.com/maykinmedia, and we are willing to maintain django-cookie-consent

For more context, see also: https://github.com/jazzband/django-cookie-consent/issues/64#issuecomment-1537141716

**Comment by jezdez** [comment]
Hey there, I just left a comment in #336 as I didn't really see an explanation for the request there, and it's a little concerning that you didn't provide one either.

Since https://github.com/jazzband/django-cookie-consent/issues/64 hasn't even been finished, I'm hard-pressed to see this ticket here as the next sensible course of action.

**Comment by sergei-maertens** [comment]
I understand that there's a lot to read through, but I feel that the linked comment in jazzband/cookie-consent#64 (and that entire) thread paints a clear picture of the frustrating experience we've had.

To summarize it:

* we can't complete the checklist to transfer to jazzband, because
    *  the project lead (me) is not being added/configured and as far as I can see on the website I cannot make myself lead
    * the readthedocs bot invite is not being invited before it expires
* git tags aren't publishing properly to the staging PyPI and all I see is a generic HTTP 500 error without any clue if this is something I can fix, nor is anyone with insight into these logs/environments giving necessary insight. it's guesswork why things are failing
* ultimately, all of this is blocking us from releasing a new version to PyPI
* users are installing old, broken versions from PyPI and (rightfully so) creating github issues and additional maintainer noise, as the underlying issues *have* been fixed but not published

I just want the ability to properly maintain and release the software. Whether that's through jazzband or not is really irrelevant for me.

**Comment by jezdez** [comment]
As I just noticed in https://github.com/jazzband/django-cookie-consent/issues/64, this was indeed the main problem: the project lead hadn't been assigned yet in the database, the release secret for the staging server hadn't been added yet and that in effect led to the situation you describe.

I've rectified both problems now, you're the project lead as previously decided already and can now do tagged releases to the staging index to do releases to PyPI.

**Comment by sergei-maertens** [comment]
Awesome, thanks for following up on this! I hope to find some time this week to try this all out. I'm closing this issue as I'm confident this will resolve the problems.
