### ISSUE TITLE
Transfer Out: django-payments

### ISSUE THREAD

**Issue by WhyNotHugo** [jazzband-roadies/help#338]
I'm the main developer of the project, and permission issues have multiple times blocked me from moving forward. (e.g.: see: https://github.com/jazzband/help/issues/329)

Currently, I need someone else with write permission to approve code changes before merging them, but there are no other active developers with write permission for this project, and I mainly have to wait (sometimes for a long time) for someone to come around and approve them (see, for example, this simple one-liner: https://github.com/jazzband/django-payments/pull/340/files).

While this is a trivial change, it's been months since my request to update it with no news, and before it some other trivial change was necessary that mostly blocked development for a long time. This has brought motivation on my part substantially down, since I know that I'll quickly become blocked again.

This has been made worse mostly due to https://github.com/jazzband/help/issues/196.

I've been considering this request for months now. While I've often opted to wait and see if the situation improves, it is unclear if that will be any time soon.

I'd like to transfer the repository out of Jazzband directly to my GitHub username.

**Comment by jezdez** [comment]
Just want to acknowledge that I've seen the issue and will have time at the end of the week to work through the process (like #337 and #336).

**Comment by WhyNotHugo** [comment]
With some recent changes and devs stepping up to help, I'll leave this on hold for now. If we can form a community here that would be best :)
