### ISSUE TITLE
Make a Django Debug Toolbar project publically visible

### ISSUE THREAD

**Issue by tim-schilling** [jazzband-roadies/help#339]
The project for the toolbar's work to make it async compatible is private and can only be made public by an organization admin.

https://github.com/orgs/jazzband/projects/9/settings

@jezdez can you update this setting for us?

cc: @matthiask

**Comment by jezdez** [comment]
Done!

**Comment by tim-schilling** [comment]
Thank you @jezdez!

**Comment by kazukitanaka78** [comment]
That's great!
