### ISSUE TITLE
Transfer Out: PrettyTable

### ISSUE THREAD

**Issue by hugovk** [jazzband-roadies/help#340]
Please could we transfer https://github.com/jazzband/prettytable to my own account? (I might move it to an org account later.) For two reasons: I'd like to set up more automation, including PyPI trusted publishing, for which I'll need regular access to the admin permissions, and also to apply for Tidelift.

Separately, my offer still stands to help out with some of the Roadie GitHub things (re: https://github.com/jazzband/help/issues/196#issuecomment-1348502900), so we can pick that up elsewhere.

**Comment by hugovk** [comment]
Ping @jezdez, if you get a chance to check this. Thanks.

**Comment by jezdez** [comment]
@hugovk 

> hugovk/prettytable already exists and You can only transfer a repository from an organization to yourself at this time

**Comment by hugovk** [comment]
I've just renamed hugovk/prettytable to hugovk/prettytable-fork, please could you try again? 

Otherwise I can delete the fork.

**Comment by hugovk** [comment]
I've transferred it out of my account into a test org.

**Comment by jezdez** [comment]
Just requested the transfer to you (via my account)

**Comment by hugovk** [comment]
Accepted, thanks! 

Please can you also give me admin on https://pypi.org/project/prettytable/? I'm hugovk there too.

**Comment by jezdez** [comment]
@flaper87 will have to provide those admin permissions, I don't have them

**Comment by hugovk** [comment]
I emailed @flaper87 and this is now set up.

I think everything is ready now, thank you very much for your help!
