### ISSUE TITLE
PyPI Release: django-simple-history v3.4.0

### ISSUE THREAD

**Issue by ddabble** [jazzband-roadies/help#344]
Version 3.4.0 of [`django-simple-history`](https://github.com/jazzband/django-simple-history) was uploaded to the Jazzband package index August 17th. The project leads [have been contacted](https://github.com/jazzband/django-simple-history/pull/1230#issuecomment-1690469616), but have yet to respond.

**Comment by bschollnick** [comment]
Any idea on the time frame for this release?

**Comment by ddabble** [comment]
@jezdez @treyhunner @rossmechanic Any of you available to publish? 🙂

**Comment by treyhunner** [comment]
It's now on PyPI. Thanks for the gentle pings @ddabble!
