### ISSUE TITLE
Jazzband.co SSL certificate incorrect and redirects to https://geschichten.leidel.info/

### ISSUE THREAD

**Issue by dopry** [jazzband-roadies/help#346]
**Describe the bug**
Jazzband.co SSL certificate incorrect and redirects to https://geschichten.leidel.info/?password-protected=login&redirect_to=https%3A%2F%2Fgeschichten.leidel.info%2F

**To Reproduce**
open jazzband.co in your browser.
you'll get an ssl invalid message, then if you choosed to proceed anyway you will be redirected to  https://geschichten.leidel.info/?password-protected=login&redirect_to=https%3A%2F%2Fgeschichten.leidel.info%2F

**Expected behavior**
jazzband.co loads.

**Comment by hugovk** [comment]
Looks like https://jazzband.co is now back up and running. 🚀 🎈
