### ISSUE TITLE
Proposal: Django-Polymorphic

### ISSUE THREAD

**Issue by j-antunes** [jazzband-roadies/help#348]
# Project Proposal

Project in question: https://github.com/django-polymorphic/django-polymorphic

## Project Details
I am not the owner of the project but I actively use it. The maintainers are not responsive for a while not, PRs and issues are starting to stack. See issue: https://github.com/django-polymorphic/django-polymorphic/issues/548

There is someone that is responsive that has write access to the project.

## Project Description
This package allows the use of polymorphic objects within Django.

## Project Leads
Me

## Confirmation of Guidelines

Please confirm the following:

- [x] I am the project owner, or have permission from the project owner, to request a transfer.  

- [X] This project is a [viable candidate](https://jazzband.co/about/guidelines#viability) for Jazzband.

- [X] This project fulfills the [documentation requirements](https://jazzband.co/about/guidelines#documentation).

- [X] This project is [tested](https://jazzband.co/about/guidelines#tests).

- [X] I am happy to adopt Jazzband's [code of conduct](https://jazzband.co/about/guidelines#conduct) in this project.

- [X] I am happy to include Jazzband's [contributing guidelines](https://jazzband.co/about/guidelines#contributing-guidelines) in this project.

**Comment by alphatownsman** [comment]
This is very useful project. I use it daily. Will contribute if it's moved here.

**Comment by gsalkin** [comment]
Big user of this package and would love to see continued development. Would love to contribute under jazzband's guidance

**Comment by vdboor** [comment]
Hi! As "maintainer" of django-polymorphic I fully endorse this move. It has been difficult for me to do contributions, as my life also changed (in a good way). So if there is anything needed on my end, I'd be happy to help.

**Comment by hugovk** [comment]
You might be better off trying with your own org, there's unfortunately an admin bottleneck at Jazzband. See also:
* https://github.com/jazzband/help/issues/196
* https://github.com/django-guardian/django-guardian/issues/759#issuecomment-1814827756

**Comment by vdboor** [comment]
Well, that turned out to be really hard, and I became the bottleneck here, despite having added some extra maintainers. Looking at the options, I think a transfer is still viable. Plus, I made sure my admin permissions are associated with the repo, and not just through the organization. So if needed I can still move it back out too.

In summary: I've just transferred django-polymorphic to jazzband.

**Comment by j-antunes** [comment]
Thank you!

**Comment by gsalkin** [comment]
Wow, this is so awesome. Love seeing great stewardship of the package!

**Comment by hugovk** [comment]
For reference, the checklist: https://github.com/jazzband/django-polymorphic/issues/553
