### ISSUE TITLE
Please block spammer

### ISSUE THREAD

**Issue by claudep** [jazzband-roadies/help#352]
See https://github.com/jazzband/django-two-factor-auth/pull/687 and https://github.com/jazzband/django-two-factor-auth/issues/688

**Comment by claudep** [comment]
I'm also missing permissions to delete those issues (https://docs.github.com/en/issues/tracking-your-work-with-issues/deleting-an-issue).

**Comment by hugovk** [comment]
Looks like GitHub has deleted those issues, presumably because they deleted the spammer's account. Shall we close this issue?

**Comment by claudep** [comment]
Thanks for noticing, I'll close now. However, it would be great to have more reactivity for these sort of incidents in the Jazzband projects, otherwise some links to bad content can remain publicly during several weeks in ticket comments.

**Comment by hugovk** [comment]
Agreed, see https://github.com/jazzband/help/issues/196.
