### ISSUE TITLE
Project Lead: django-configurations

### ISSUE THREAD

**Issue by pauloxnet** [jazzband-roadies/help#354]
# Project lead request

I started contributing to the [django-configurations](https://github.com/jazzband/django-configurations) project in 2019 and since then I have collaborated in keeping the project active and updated.

I released the [latest version](https://github.com/jazzband/django-configurations/releases/tag/2.5.1) of the project in November 2023, but since then none of the leads have released the version on PyPi, despite a specific [issue](https://github.com/jazzband/django-configurations/issues/378) of mine, I guess due to time constraints.

I'm applying as lead of Django Configurations because I think I can help the current leads in reviewing and publishing new versions on PyPi, as well as continue to give my contribution.

CC @jezdez @blueyed

**Comment by jezdez** [comment]
I think that's a great idea!

**Comment by jezdez** [comment]
https://jazzband.co/projects/django-configurations
