### ISSUE TITLE
PyPI Release: django-model-utils 4.4.0

### ISSUE THREAD

**Issue by shanx** [jazzband-roadies/help#357]
Hey there @jezdez! How's life. It has been a while, Remco here :) 

I was trying to help out a bit as part of jazzband to get a new release of `django-model-utils` out there. The release process has been automated (mostly by you it seems), but it looks like it is not currently fully working: https://github.com/jazzband/django-model-utils/actions/runs/7856043884/job/21438400809 

Anything I can do to have that release correctly published to PyPI?

Thanks!

**Comment by hugovk** [comment]
The files were correctly uploaded to the Jazzband staging area:

https://github.com/jazzband/django-model-utils/actions/runs/7856043884/job/21438400809#step:7:51

The next step is for a project lead to log in to the Jazzband website to release the files from the staging area to PyPI.

See https://jazzband.co/about/releases for details. 

The project leads listed at https://jazzband.co/projects/django-model-utils are @charettes and @carljm.

**Comment by charettes** [comment]
Just released the staged uploads so I'll close this one. Thank you for submitting it @shanx

**Comment by shanx** [comment]
Thanks a lot @charettes!

**Comment by shanx** [comment]
Sorry misclicked
