### ISSUE TITLE
PyPI Release: django-pipeline 3.1.0

### ISSUE THREAD

**Issue by davidt** [jazzband-roadies/help#363]
django-pipeline is currently thoroughly broken for Django 4+, and 3.2 is now EOL. I have pushed a 3.1.0 but nobody has been available to promote the release.

I have a pending request to be made a project lead so I can do this myself, but that seems like it's possibly a larger task. In the meantime, can we get 3.1 published to PyPI please?

**Comment by hugovk** [comment]
cc @peymanslh and @cyberdelia as project leads, listed at https://jazzband.co/projects/django-pipeline, who can make releases.

**Comment by peymanslh** [comment]
Hi, 
Sorry for late response, I'll check and prepare the release tomorrow

**Comment by cyberdelia** [comment]
I already approved it 😇

**Comment by davidt** [comment]
Thanks!

**Comment by cyberdelia** [comment]
@davidt Happy to start the process to make you a lead as well, if you're interested.

**Comment by davidt** [comment]
Very interested! I posted a bug #361 asking to do that but @jezdez is surely overwhelmed.
