### ISSUE TITLE
Project Lead: django-constance

### ISSUE THREAD

**Issue by Mogost** [jazzband-roadies/help#365]
# Project lead request

Hello,
I would like to join the django-constance project as a lead, especially in consideration of the changes discussed in [issue #364](https://github.com/jazzband/help/issues/364). I actively use this package, and its security is a top priority for me.

My code-contributions can be viewed here: [Mogost's commits on django-constance](https://github.com/jazzband/django-constance/commits?author=Mogost).
Additionally, I actively participate in reviews and discussions:
![image](https://github.com/jazzband/help/assets/721963/4fbe5dcd-b5ea-40d5-97e1-83fc0cd5bfbc)

I am closely monitoring all the ongoing changes to this package.

Thank you for considering my request.

**Comment by Mogost** [comment]
I'd like to mention that I've had a significant increase in contributions to `django-constance` recently.
especially the big change https://github.com/jazzband/django-constance/pull/564
ping @jezdez @jazzband/roadies

**Comment by jezdez** [comment]
@camilonova @Natim Do you concur?

**Comment by camilonova** [comment]
@jezdez I support his nomination

**Comment by Natim** [comment]
@jezdez likewise :pray:

 @Mogost did all three last releases, I just validated the push to PyPI in order to keep both Github and PyPI in sync, but I believe it is best if @Mogost can do it himself.

**Comment by Mogost** [comment]
@jezdez can this move forward?

There is a next release pending and waiting for approval https://github.com/jazzband/django-constance/releases/tag/4.1.2
It would be great if I could approve it 😄

**Comment by Natim** [comment]
@jezdez today again I had to validate myself with a 15h delay the release made by @Mogost, I would be glad if you could configure his account so that he can be autonomous doing them.

Best regards,

Rémy

**Comment by jezdez** [comment]
Thanks for the comments everyone, this is now done. https://jazzband.co/projects/django-constance

**Comment by Natim** [comment]
Thanks Janis!
