### ISSUE TITLE
Transfer out: django-debug-toolbar

### ISSUE THREAD

**Issue by tim-schilling** [jazzband-roadies/help#369]
# Project Proposal

We're looking to move [django-debug-toolbar](https://github.com/jazzband/django-debug-toolbar) to the [Django Commons organization](https://github.com/django-commons).

## Project Details
django-debug-toolbar

## Project Description
Please coordinate with ~~@cunla~~ @tim-schilling for transferring the repository

## Related Issues

Django Commons transfer issue: https://github.com/django-commons/membership/issues/34
Debug Toolbar discussion issue: https://github.com/jazzband/django-debug-toolbar/issues/1918

**Comment by tim-schilling** [comment]
Hi @jezdez, do you have a rough estimate of when you'll have time for this?

**Comment by tim-schilling** [comment]
@jezdez The main task I have remaining is transfering the GitHub org to my account so I can transfer it into Django Commons. We don't need to do that synchronously. Would you have time to initiate that transfer to my account in the next week?

https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository

**Comment by jezdez** [comment]
@tim-schilling Sounds good, I just tried to initiate it and GitHub responded with:

> tim-schilling/django-debug-toolbar already exists and You can only transfer a repository from an organization to yourself at this time

and when I tried `django-commons`:

> You don’t have the permission to create public repositories on django-commons

**Comment by tim-schilling** [comment]
Ack. Sorry about that. I renamed my clone. Can you try again? If that doesn't work I'll delete it.

**Comment by jezdez** [comment]
> tim-schilling already has a repository in the jazzband/django-debug-toolbar network and You can only transfer a repository from an organization to yourself at this time

**Comment by tim-schilling** [comment]
Deleted the repo.

**Comment by jezdez** [comment]
I think this triggered a limit, I now get:

> You can only transfer a repository from an organization to yourself at this time

**Comment by jezdez** [comment]
I'll try later again

**Comment by tim-schilling** [comment]
We can add you to django commons so you can transfer it directly in too. I'll get that setup, the invite lasts a week if that the route you want to take.

**Comment by tim-schilling** [comment]
I thought you'd be able to transfer it to me out of an org, but I guess not. It might need to go Jazzband -> jezdez -> tim-schilling -> django-commons

**Comment by jezdez** [comment]
@tim-schilling just requested the transfer to you (from my account), seems like it wasn't sufficient for me to be added to django-commons 🤷🏻

**Comment by tim-schilling** [comment]
Accepted. Thank you @jezdez! I wish GitHub was incentivized to make this easy, but I'm glad we found a working solution.

**Comment by jezdez** [comment]
> Accepted. Thank you @jezdez! I wish GitHub was incentivized to make this easy, but I'm glad we found a working solution.

No problem, ironically this has been hard ever since Jazzband existed, usually when I onboarded projects, and I've come to accept that GitHub just doesn't care that much about it. I've spoken about that with their support a number of times over the years

**Comment by tim-schilling** [comment]
That's frustrating, but good for setting expectations.
