### ISSUE TITLE
Can't login in jazzband.co

### ISSUE THREAD

**Issue by andruten** [jazzband-roadies/help#377]
Hi! 👋 

I'm trying to release a `django-revproxy` upload but I'm not able to login in the jazzband.co site. When I click on "Authorize Jazzband-bot" it redirects multiple times and displays:
> This application has made an unusually high number of requests to access your account. Please reauthorize the application to continue.

<img width="537" alt="Captura de pantalla 2024-11-06 a las 0 07 33" src="https://github.com/user-attachments/assets/0f4f0486-3862-44ec-bc94-8768bf7ef877">

Also, it says `Access request pending`. Is that normal? 

<img width="473" alt="Captura de pantalla 2024-11-06 a las 0 07 41" src="https://github.com/user-attachments/assets/21ba28f1-7a09-49c2-bffd-5b387604db74">

Finally, I see this:
<img width="348" alt="Captura de pantalla 2024-11-06 a las 0 13 53" src="https://github.com/user-attachments/assets/3731be85-4fb2-4203-80d1-73c477dedf4e">

I've released a couple of uploads in the past but it seems I'm not able to do it anymore 😢 

Can anyone help?

Thanks in advance!

**Comment by andruten** [comment]
I tried again yesterday and it worked fine. 🤷

**Comment by jezdez** [comment]
This is a known issue with the GitHub API for the record

**Comment by andruten** [comment]
Thank you for letting me know. I'm closing the issue.
