### ISSUE TITLE
PyPI Release: django-smart-selects

### ISSUE THREAD

**Issue by androettop** [jazzband-roadies/help#380]
Hello, I need version 1.7.2 of django-smart-selects released on PyPI. This version includes important fixes for compatibility with newer Django versions. I tried reaching out to the project leads but haven’t received a response.

PR: https://github.com/jazzband/django-smart-selects/pull/359
Release: https://github.com/jazzband/django-smart-selects/releases/tag/1.7.2

Thank you for your help.

cc: @digi604 @manelclos

**Comment by manelclos** [comment]
Hi @androettop, thanks a lot. The 1.7.2 release is now on pypi: https://pypi.org/project/django-smart-selects/
