### ISSUE TITLE
PyPI Release: django-newsletter

### ISSUE THREAD

**Issue by sebastian-muthwill** [jazzband-roadies/help#383]
Hey I would like to publish a new version v1.0 which adds support for all most recent versions of Python and Django and removes all versions which are EOL. Since I could not identify a project lead I create this issue here. 
Since it is my first PR here I would appreciate if you could check the PR and kindly address any mistakes. I tried to follow the guideline as close as possible.
 
PR: https://github.com/jazzband/django-newsletter/pull/394
Release: https://github.com/jazzband/django-newsletter/releases/tag/v1.0

**Comment by hugovk** [comment]
The project lead is listed at https://jazzband.co/projects/django-newsletter.

@dokterbob Can you help with a release?

**Comment by dokterbob** [comment]
It's done! Thanks for the poke.

**Comment by dokterbob** [comment]
Might wanna bump the changelog a bit as well...

**Comment by sebastian-muthwill** [comment]
Thanks @dokterbob
