### ISSUE TITLE
Allow Jazzband members to abort/restart build on Appveyor

### ISSUE THREAD

**Issue by vphilippon** [jazzband-roadies/help#74]
It looks like we have limited actions on appveyor, compared to travis-ci.

Is it possible to allow members to abort/restart builds on appveyor?

**Comment by jezdez** [comment]
So I've had to move the pip-tools Appveyor setup from account based of the jazzband-bot account to be "team based", as documented here: https://www.appveyor.com/docs/team-setup/#permissions

That means, build show up now here: https://ci.appveyor.com/project/jazzband/pip-tools and not https://ci.appveyor.com/project/jazzband-bot/pip-tools anymore. Links to old builds seem to continue to work though, so existing PRs and their builds continue to work until the next commit at which the URL of the build will change.

I've mapped the Jazzband members team to an Appveyor User role, and gave the User role permission to view and run builds for the pip-tools repo.

I hope this is what you had in mind, this is more complicated than anticipated :) Let me know if you see weird things..

**Comment by jezdez** [comment]
FTR, I just manually triggered the "first" build for that new setup: https://ci.appveyor.com/project/jazzband/pip-tools/build/1.0.1

**Comment by vphilippon** [comment]
Thank you for your work!

>I've mapped the Jazzband members team to an Appveyor User role, and gave the User role permission to view and run builds for the pip-tools repo.

Somehow, I can't find where to manually trigger the build myself.
Then again, I can't see anywhere that I'm somehow linked to the Jazzband team either. Do you know If I should be able to verify that somewhere?

**Comment by jezdez** [comment]
Hm, you're right, when I tried reproducing the build link, I couldn't. It should appear on https://ci.appveyor.com/project/jazzband/pip-tools I think.

I followed the docs and mapped the GitHub members team to a Appveyor team that has the permissions to run a build. I'm afraid that's all I see from my end :-/

I've written to the Appveyor support and asked if we're missing a crucial thing for this to work.

**Comment by vphilippon** [comment]
From our discussion on IRC (Posting back here, as I remembered I'm not getting offline messages on IRC...).
> Their support responded
"Make sure your colleague is logging in into "jazzband" (drop down on AppVeyor's Sign in page)."
So when you sign in, click on the github button
and then it should offer you again a dropdown which profile you want to login into
either your account or the jazzband organization

Related screenshot
https://jzdz.me/PBmvgUdtuYXbFctKFplT/

But I never get to see this dropdown list. Whenever I login with github, I have the github "pop-up" (If I wasn't previously logged on github), and I get directly to my account.

**Comment by vphilippon** [comment]
Looking into this, I noted something: There are 2 Appveyor  "OAuth" apps: `Appveyor` and `Appveyor-CI`.
- `Appveyor-CI` seems to be the one required to trigger the CI. It has all its required right granted, including on the jazzband organization.
- `Appveyor` seems to be the one that allows me to connect with my github account. This one does *not* have all its right granted on the Jazzband organization. Could it be it? Should I click on that "request" button?

**Comment by jezdez** [comment]
AppVeyor is now removed from pip-tools (and in effect from Jazzband).
